LABEL_FIELD: label
benchmark_filename:
- train
- valid
- test
checkpoint_dir: saved_dbbook
data_path: dataset/
dataset: dbbook
model: 'MultiVAE'
epochs: 50
train_batch_size: 1024
learner: adam
learning_rate: 0.001
eval_step: 1
stopping_step: 10000
seed: 42